export const MOCK_MINIONS = [
  {
    id: "cat",
    name: "Cat Courier",
    emoji: "🐱",
    icon: "cat",
    type: "manual",
    ownerType: "system_default",
    source: "Default",
    active: true,
    slotIndex: 0,
    status: "active",
    command: "!sendcat",
    description: "Speak the word after the summon and the beast takes its shape. Lawyer. Wizard. Tax auditor. A miserable little pantheon of cats.",
    destination: "Discord · #cat-chaos",
    destinationProvider: "discord",
    version: "v1.0 default",
    currentVersionId: "v-cat-1",
    triggerType: "manual",
    exampleInput: "!sendcat lawyer",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-14T00:00:00Z",
  },
  {
    id: "brief",
    name: "Brief Wraith",
    emoji: "📜",
    icon: "mail",
    type: "auto",
    ownerType: "system_default",
    source: "Default",
    active: true,
    slotIndex: 1,
    status: "active",
    command: "",
    description: "It prowls the morning docket and drags back deadlines before they rot.",
    destination: "Email · inbox",
    destinationProvider: "email",
    version: "v1.0 default",
    currentVersionId: "v-brief-1",
    triggerType: "automatic",
    interval: "Daily at 8:30 AM",
    nextRun: "Tomorrow · 8:30 AM",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-14T00:00:00Z",
  },
  {
    id: "social",
    name: "Social Imp",
    emoji: "📣",
    icon: "chat",
    type: "auto",
    ownerType: "user_owned",
    source: "User",
    active: true,
    slotIndex: 2,
    status: "active",
    command: "",
    description: "A tiny herald with too much confidence. It posts when the clock permits.",
    destination: "Telegram · private bot chat",
    destinationProvider: "telegram",
    version: "v3 user",
    currentVersionId: "v-social-3",
    triggerType: "automatic",
    interval: "Every 5 hours",
    nextRun: "Today · 5:00 PM",
    createdAt: "2026-06-05T00:00:00Z",
    updatedAt: "2026-06-14T00:00:00Z",
  },
  {
    id: "invoice",
    name: "Invoice Ghoul",
    emoji: "📋",
    icon: "task",
    type: "manual",
    ownerType: "user_owned",
    source: "User",
    active: false,
    slotIndex: null,
    status: "inactive",
    command: "!invoice",
    description: "It sniffs out receipts and arranges them into something almost respectable.",
    destination: "Gmail · drafts",
    destinationProvider: "email",
    version: "v2 user",
    currentVersionId: "v-invoice-2",
    triggerType: "manual",
    exampleInput: "!invoice client",
    createdAt: "2026-06-03T00:00:00Z",
    updatedAt: "2026-06-12T00:00:00Z",
  },
  {
    id: "weather",
    name: "Weather Oracle",
    emoji: "✨",
    icon: "sparkles",
    type: "auto",
    ownerType: "system_default",
    source: "Default",
    active: false,
    slotIndex: null,
    status: "inactive",
    command: "",
    description: "Looks upward, complains, and tells you whether the sky intends betrayal.",
    destination: "Telegram · private bot chat",
    destinationProvider: "telegram",
    version: "v1.0 default",
    currentVersionId: "v-weather-1",
    triggerType: "automatic",
    interval: "Daily at 7:00 AM",
    nextRun: "Tomorrow · 7:00 AM",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-10T00:00:00Z",
  },
  {
    id: "law",
    name: "Law Goblin",
    emoji: "🛡️",
    icon: "shield",
    type: "manual",
    ownerType: "user_owned",
    source: "User",
    active: false,
    slotIndex: null,
    status: "inactive",
    command: "!lawgoblin",
    description: "A small clerk-beast that remembers procedural misery better than it should.",
    destination: "Hades chat",
    destinationProvider: "hades_chat",
    version: "v4 user",
    currentVersionId: "v-law-4",
    triggerType: "manual",
    exampleInput: "!lawgoblin queens pc",
    createdAt: "2026-06-02T00:00:00Z",
    updatedAt: "2026-06-11T00:00:00Z",
  },
  {
    id: "meme",
    name: "Meme Furnace",
    emoji: "✨",
    icon: "sparkles",
    type: "manual",
    ownerType: "system_default",
    source: "Default",
    active: false,
    slotIndex: null,
    status: "inactive",
    command: "!meme",
    description: "Throws your phrase into the furnace and returns culture. Usually damaged.",
    destination: "Discord · private test",
    destinationProvider: "discord",
    version: "v1.0 default",
    currentVersionId: "v-meme-1",
    triggerType: "manual",
    exampleInput: "!meme tired developer",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-09T00:00:00Z",
  },
  {
    id: "calendar",
    name: "Calendar Shade",
    emoji: "🏢",
    icon: "building2",
    type: "auto",
    ownerType: "system_default",
    source: "Default",
    active: false,
    slotIndex: null,
    status: "inactive",
    command: "",
    description: "Counts the hours. Judges your optimism. Sends reminders anyway.",
    destination: "Email · calendar digest",
    destinationProvider: "email",
    version: "v1.0 default",
    currentVersionId: "v-calendar-1",
    triggerType: "automatic",
    interval: "Weekdays at 6:00 PM",
    nextRun: "Monday · 6:00 PM",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-08T00:00:00Z",
  },
  {
    id: "tea",
    name: "Tea Familiar",
    emoji: "🍵",
    icon: "sparkles",
    type: "auto",
    ownerType: "user_owned",
    source: "User",
    active: false,
    slotIndex: null,
    status: "inactive",
    command: "",
    description: "Summons caffeine reminders with the gravity of an ancient curse.",
    destination: "Telegram · private bot chat",
    destinationProvider: "telegram",
    version: "v1 user",
    currentVersionId: "v-tea-1",
    triggerType: "automatic",
    interval: "Every 3 hours",
    nextRun: "Today · 4:15 PM",
    createdAt: "2026-06-06T00:00:00Z",
    updatedAt: "2026-06-10T00:00:00Z",
  },
  {
    id: "job",
    name: "Job Harpy",
    emoji: "🦅",
    icon: "mail",
    type: "auto",
    ownerType: "user_owned",
    source: "User",
    active: false,
    slotIndex: null,
    status: "inactive",
    command: "",
    description: "Screeches when a role appears. Occasionally useful. Often rude.",
    destination: "Email · job alerts",
    destinationProvider: "email",
    version: "v5 user",
    currentVersionId: "v-job-5",
    triggerType: "automatic",
    interval: "Daily at 10:00 AM",
    nextRun: "Tomorrow · 10:00 AM",
    createdAt: "2026-06-07T00:00:00Z",
    updatedAt: "2026-06-13T00:00:00Z",
  },
  {
    id: "pdf",
    name: "PDF Imp",
    emoji: "📄",
    icon: "task",
    type: "manual",
    ownerType: "system_default",
    source: "Default",
    active: false,
    slotIndex: null,
    status: "inactive",
    command: "!pdfimp",
    description: "Chews documents. Spits out order. A disgusting but practical miracle.",
    destination: "Hades chat",
    destinationProvider: "hades_chat",
    version: "v1.0 default",
    currentVersionId: "v-pdf-1",
    triggerType: "manual",
    exampleInput: "!pdfimp summarize",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-05T00:00:00Z",
  },
  {
    id: "empty1",
    name: "Empty Husk",
    emoji: "🕳️",
    icon: "sparkles",
    type: "manual",
    ownerType: "system_default",
    source: "Default",
    active: false,
    slotIndex: null,
    status: "inactive",
    command: "!husk",
    description: "Mostly decorative. Still less useless than a meeting.",
    destination: "Hades chat",
    destinationProvider: "hades_chat",
    version: "v1.0 default",
    currentVersionId: "v-empty1-1",
    triggerType: "manual",
    exampleInput: "!husk awaken",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
];

export const MOCK_LOGS = [
  { id: "l1", minionId: "cat", minionName: "Cat Courier", runType: "manual", status: "success", destinationProvider: "discord", destinationLabel: "Discord · #cat-chaos", friendlyTime: "Today · 2:14 PM", exactTimestamp: "2026-06-14T14:14:32-04:00", dateGroup: "Today", summary: "Lawyer cat GIF sent.", unread: true, version: "v1.0 default", owner: "you", externalMessageUrl: "https://discord.com/channels/example/cat-chaos/l1", openLabel: "Open Discord message" },
  { id: "l2", minionId: "cat", minionName: "Cat Courier", runType: "test", status: "success", destinationProvider: "telegram", destinationLabel: "Telegram private", friendlyTime: "Today · 1:02 PM", exactTimestamp: "2026-06-14T13:02:09-04:00", dateGroup: "Today", summary: "Wizard cat test delivered.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: "https://t.me/hades_test_bot", openLabel: "Open Telegram chat" },
  { id: "l3", minionId: "brief", minionName: "Brief Wraith", runType: "auto", status: "success", destinationProvider: "email", destinationLabel: "Email · inbox", friendlyTime: "Today · 8:30 AM", exactTimestamp: "2026-06-14T08:30:02-04:00", dateGroup: "Today", summary: "Morning docket digest sent.", unread: true, version: "v1.0 default", owner: "you", externalMessageUrl: "https://mail.google.com/mail/u/0/#inbox/example-thread", openLabel: "Open email thread" },
  { id: "l4", minionId: "social", minionName: "Social Imp", runType: "auto", status: "failed", destinationProvider: "telegram", destinationLabel: "Telegram private", friendlyTime: "Today · 7:00 AM", exactTimestamp: "2026-06-14T07:00:01-04:00", dateGroup: "Today", summary: "Telegram delivery failed.", unread: true, version: "v3 user", owner: "you", externalMessageUrl: "https://t.me/hades_test_bot", openLabel: "Open Telegram chat" },
  { id: "l5", minionId: "cat", minionName: "Cat Courier", runType: "manual", status: "success", destinationProvider: "discord", destinationLabel: "Discord · #cat-chaos", friendlyTime: "Yesterday · 4:44 PM", exactTimestamp: "2026-06-13T16:44:18-04:00", dateGroup: "Yesterday", summary: "Tax-auditor cat sent.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: "https://discord.com/channels/example/cat-chaos/l5", openLabel: "Open Discord message" },
  { id: "l6", minionId: "cat", minionName: "Cat Courier", runType: "manual", status: "cancelled", destinationProvider: "preview", destinationLabel: "Preview", friendlyTime: "Yesterday · 1:12 PM", exactTimestamp: "2026-06-13T13:12:44-04:00", dateGroup: "Yesterday", summary: "Private send cancelled.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: null, openLabel: null },
  { id: "l7", minionId: "brief", minionName: "Brief Wraith", runType: "auto", status: "success", destinationProvider: "email", destinationLabel: "Email · inbox", friendlyTime: "Yesterday · 8:30 AM", exactTimestamp: "2026-06-13T08:30:00-04:00", dateGroup: "Yesterday", summary: "Deadline digest sent.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: "https://mail.google.com/mail/u/0/#inbox/example-thread-2", openLabel: "Open email thread" },
  { id: "l8", minionId: "cat", minionName: "Cat Courier", runType: "manual", status: "success", destinationProvider: "discord", destinationLabel: "Discord · #cat-chaos", friendlyTime: "Jun 13 · 2:03 PM", exactTimestamp: "2026-06-13T14:03:11-04:00", dateGroup: "Jun 13, 2026", summary: "Wizard cat GIF sent.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: "https://discord.com/channels/example/cat-chaos/l8", openLabel: "Open Discord message" },
  { id: "l9", minionId: "invoice", minionName: "Invoice Ghoul", runType: "manual", status: "success", destinationProvider: "email", destinationLabel: "Gmail · drafts", friendlyTime: "Jun 13 · 11:22 AM", exactTimestamp: "2026-06-13T11:22:45-04:00", dateGroup: "Jun 13, 2026", summary: "Invoice email draft created.", unread: true, version: "v2 user", owner: "you", externalMessageUrl: "https://mail.google.com/mail/u/0/#drafts", openLabel: "Open Gmail draft" },
  { id: "l10", minionId: "law", minionName: "Law Goblin", runType: "manual", status: "success", destinationProvider: "hades_chat", destinationLabel: "Hades chat", friendlyTime: "Jun 12 · 6:12 PM", exactTimestamp: "2026-06-12T18:12:03-04:00", dateGroup: "Jun 12, 2026", summary: "Citation goblin answered in chat.", unread: false, version: "v1 user", owner: "you", externalMessageUrl: null, openLabel: null },
  { id: "l11", minionId: "cat", minionName: "Cat Courier", runType: "test", status: "success", destinationProvider: "email", destinationLabel: "Email · self", friendlyTime: "Jun 12 · 5:20 PM", exactTimestamp: "2026-06-12T17:20:56-04:00", dateGroup: "Jun 12, 2026", summary: "Pirate cat test emailed.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: "https://mail.google.com/mail/u/0/#inbox/example-thread-3", openLabel: "Open email thread" },
  { id: "l12", minionId: "cat", minionName: "Cat Courier", runType: "manual", status: "blocked", destinationProvider: "discord", destinationLabel: "Discord · #cat-chaos", friendlyTime: "Jun 12 · 3:00 PM", exactTimestamp: "2026-06-12T15:00:10-04:00", dateGroup: "Jun 12, 2026", summary: "Blocked because minion was inactive.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: null, openLabel: null },
  { id: "l13", minionId: "brief", minionName: "Brief Wraith", runType: "auto", status: "success", destinationProvider: "email", destinationLabel: "Email · inbox", friendlyTime: "Jun 12 · 8:30 AM", exactTimestamp: "2026-06-12T08:30:00-04:00", dateGroup: "Jun 12, 2026", summary: "Morning docket digest sent.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: "https://mail.google.com/mail/u/0/#inbox/example-thread-4", openLabel: "Open email thread" },
  { id: "l14", minionId: "tea", minionName: "Tea Familiar", runType: "auto", status: "success", destinationProvider: "telegram", destinationLabel: "Telegram private", friendlyTime: "Jun 11 · 4:15 PM", exactTimestamp: "2026-06-11T16:15:00-04:00", dateGroup: "Jun 11, 2026", summary: "Caffeine reminder sent.", unread: false, version: "v1 user", owner: "you", externalMessageUrl: "https://t.me/hades_test_bot", openLabel: "Open Telegram chat" },
  { id: "l15", minionId: "social", minionName: "Social Imp", runType: "auto", status: "success", destinationProvider: "telegram", destinationLabel: "Telegram private", friendlyTime: "Jun 11 · 12:00 PM", exactTimestamp: "2026-06-11T12:00:00-04:00", dateGroup: "Jun 11, 2026", summary: "Noon post reminder sent.", unread: false, version: "v3 user", owner: "you", externalMessageUrl: "https://t.me/hades_test_bot", openLabel: "Open Telegram chat" },
  { id: "l16", minionId: "calendar", minionName: "Calendar Shade", runType: "auto", status: "failed", destinationProvider: "email", destinationLabel: "Email · calendar digest", friendlyTime: "Jun 10 · 6:00 PM", exactTimestamp: "2026-06-10T18:00:00-04:00", dateGroup: "Jun 10, 2026", summary: "Calendar digest failed.", unread: true, version: "v1.0 default", owner: "you", externalMessageUrl: "mailto:", openLabel: "Open email app" },
  { id: "l17", minionId: "weather", minionName: "Weather Oracle", runType: "auto", status: "success", destinationProvider: "telegram", destinationLabel: "Telegram private", friendlyTime: "Jun 10 · 7:00 AM", exactTimestamp: "2026-06-10T07:00:00-04:00", dateGroup: "Jun 10, 2026", summary: "Weather notice sent.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: "https://t.me/hades_test_bot", openLabel: "Open Telegram chat" },
  { id: "l18", minionId: "tea", minionName: "Tea Familiar", runType: "auto", status: "success", destinationProvider: "telegram", destinationLabel: "Telegram private", friendlyTime: "Jun 8 · 4:15 PM", exactTimestamp: "2026-06-08T16:15:00-04:00", dateGroup: "Jun 8, 2026", summary: "Caffeine reminder sent.", unread: false, version: "v1 user", owner: "you", externalMessageUrl: "https://t.me/hades_test_bot", openLabel: "Open Telegram chat" },
  { id: "l19", minionId: "job", minionName: "Job Harpy", runType: "auto", status: "success", destinationProvider: "email", destinationLabel: "Email · job alerts", friendlyTime: "Jun 13 · 10:00 AM", exactTimestamp: "2026-06-13T10:00:00-04:00", dateGroup: "Jun 13, 2026", summary: "Job alert sent: 3 new roles.", unread: false, version: "v5 user", owner: "you", externalMessageUrl: "https://mail.google.com/mail/u/0/#inbox/job-alert", openLabel: "Open email" },
  { id: "l20", minionId: "job", minionName: "Job Harpy", runType: "auto", status: "failed", destinationProvider: "email", destinationLabel: "Email · job alerts", friendlyTime: "Jun 12 · 5:12 AM", exactTimestamp: "2026-06-12T10:00:00-04:00", dateGroup: "Jun 12, 2026", summary: "Harpy delivery failed - API timeout.", unread: true, version: "v5 user", owner: "you", externalMessageUrl: null, openLabel: null },
  { id: "l21", minionId: "pdf", minionName: "PDF Imp", runType: "manual", status: "success", destinationProvider: "hades_chat", destinationLabel: "Hades chat", friendlyTime: "Jun 5 · 3:30 PM", exactTimestamp: "2026-06-05T15:30:00-04:00", dateGroup: "Jun 5, 2026", summary: "Document chewed and summarized.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: null, openLabel: null },
  { id: "l22", minionId: "pdf", minionName: "PDF Imp", runType: "test", status: "success", destinationProvider: "hades_chat", destinationLabel: "Hades chat", friendlyTime: "Jun 4 · 11:00 AM", exactTimestamp: "2026-06-04T11:00:00-04:00", dateGroup: "Jun 4, 2026", summary: "Test: document chewed successfully.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: null, openLabel: null },
  { id: "l23", minionId: "meme", minionName: "Meme Furnace", runType: "manual", status: "success", destinationProvider: "discord", destinationLabel: "Discord · private test", friendlyTime: "Jun 9 · 12:00 AM", exactTimestamp: "2026-06-09T00:00:00-04:00", dateGroup: "Jun 9, 2026", summary: "Meme generated and sent.", unread: false, version: "v1.0 default", owner: "you", externalMessageUrl: null, openLabel: null },
];

export const MOCK_PREVIEWS = {
  cat: {
    minionId: "cat",
    minionVersionId: "v-cat-1",
    exampleInput: "!sendcat lawyer",
    outputText: "A lawyer cat, grave with legal delusions. It objects to the yarn and bills by the hour.",
    artifactType: "text",
    generatedAt: "2026-06-14T12:00:00Z",
    basedOnEditedAt: "2026-06-14T00:00:00Z",
    followUp: {
      input: "!hades I want a different cat",
      output: "The court permits a different beast. 🧙‍♂️",
    },
  },
  brief: {
    minionId: "brief",
    minionVersionId: "v-brief-1",
    exampleInput: "Daily at 8:30 AM",
    outputText: "Morning docket digest prepared. The deadlines have assembled like minor demons.",
    artifactType: "text",
    generatedAt: "2026-06-14T08:30:00Z",
    basedOnEditedAt: "2026-06-14T00:00:00Z",
  },
  social: {
    minionId: "social",
    minionVersionId: "v-social-3",
    exampleInput: "Every 5 hours",
    outputText: "Scheduled social note prepared for Telegram. The imp has found something to shout about.",
    artifactType: "text",
    generatedAt: "2026-06-14T12:00:00Z",
    basedOnEditedAt: "2026-06-14T00:00:00Z",
  },
  invoice: {
    minionId: "invoice",
    minionVersionId: "v-invoice-2",
    exampleInput: "!invoice client",
    outputText: "Receipts gathered. A draft invoice slouches in Gmail awaiting your approval.",
    artifactType: "text",
    generatedAt: "2026-06-13T11:22:45-04:00",
    basedOnEditedAt: "2026-06-12T00:00:00Z",
  },
  weather: {
    minionId: "weather",
    minionVersionId: "v-weather-1",
    exampleInput: "Daily at 7:00 AM",
    outputText: "The sky eyes you with suspicion. 60% chance of drizzle and mild betrayal.",
    artifactType: "text",
    generatedAt: "2026-06-10T07:00:00-04:00",
    basedOnEditedAt: "2026-06-10T00:00:00Z",
  },
  law: {
    minionId: "law",
    minionVersionId: "v-law-4",
    exampleInput: "!lawgoblin queens pc",
    outputText: "The goblin returns clutching a procedural manual. It mutters about precedents.",
    artifactType: "text",
    generatedAt: "2026-06-12T18:12:03-04:00",
    basedOnEditedAt: "2026-06-11T00:00:00Z",
  },
  meme: {
    minionId: "meme",
    minionVersionId: "v-meme-1",
    exampleInput: "!meme tired developer",
    outputText: "Generated: a crumpled stick figure labeled 'my will to live' fleeing a Jira ticket.",
    artifactType: "text",
    generatedAt: "2026-06-09T00:00:00Z",
    basedOnEditedAt: "2026-06-09T00:00:00Z",
  },
  calendar: {
    minionId: "calendar",
    minionVersionId: "v-calendar-1",
    exampleInput: "Weekdays at 6:00 PM",
    outputText: "Evening judgment rendered. The shade notes your optimism was unfounded.",
    artifactType: "text",
    generatedAt: "2026-06-10T18:00:00-04:00",
    basedOnEditedAt: "2026-06-08T00:00:00Z",
  },
  tea: {
    minionId: "tea",
    minionVersionId: "v-tea-1",
    exampleInput: "Every 3 hours",
    outputText: "Caffeine nudge dispatched. Tea Familiar insists you have abandoned your mug.",
    artifactType: "text",
    generatedAt: "2026-06-11T16:15:00-04:00",
    basedOnEditedAt: "2026-06-10T00:00:00Z",
  },
  job: {
    minionId: "job",
    minionVersionId: "v-job-5",
    exampleInput: "Daily at 10:00 AM",
    outputText: "The Harpy shrieks: three new roles detected. Two look suspect. One might be real.",
    artifactType: "text",
    generatedAt: "2026-06-13T10:00:00-04:00",
    basedOnEditedAt: "2026-06-13T00:00:00Z",
  },
  pdf: {
    minionId: "pdf",
    minionVersionId: "v-pdf-1",
    exampleInput: "!pdfimp summarize",
    outputText: "Document chewed. Pages 2-7 reduced to three bullet points. The imp looks pleased with itself.",
    artifactType: "text",
    generatedAt: "2026-06-05T00:00:00Z",
    basedOnEditedAt: "2026-06-05T00:00:00Z",
  },
  empty1: {
    minionId: "empty1",
    minionVersionId: "v-empty1-1",
    exampleInput: "!husk awaken",
    outputText: "The husk stirs. Nothing happens. It blinks once. This is its entire purpose.",
    artifactType: "text",
    generatedAt: "2026-06-01T00:00:00Z",
    basedOnEditedAt: "2026-06-01T00:00:00Z",
  },
};

export const MOCK_CONNECTED_DESTINATIONS = [
  { provider: "telegram", label: "Telegram", icon: "\u2708\uFE0F", connected: true },
  { provider: "discord", label: "Discord DM", icon: "\uD83D\uDCAC", connected: true },
  { provider: "email", label: "Email", icon: "\u2709\uFE0F", connected: true },
  { provider: "hades_chat", label: "Hades chat", icon: "\uD83D\uDD25", connected: true },
];


export function getEmojiForMinion(minion) {
  return minion?.emoji || "🐱";
}

export function getPreviewForMinion(minionId) {
  return MOCK_PREVIEWS[minionId] || null;
}

export function getLogsForMinion(minionId) {
  if (!minionId) return MOCK_LOGS;
  return MOCK_LOGS.filter((l) => l.minionId === minionId);
}

export function getRecentLogsForMinion(minionId, count = 6) {
  return getLogsForMinion(minionId).slice(0, count);
}
