import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

function full(relativePath) {
  return path.join(root, relativePath);
}

function exists(relativePath) {
  return fs.existsSync(full(relativePath));
}

function read(relativePath) {
  return fs.readFileSync(full(relativePath), "utf8");
}

function readJson(relativePath) {
  return JSON.parse(read(relativePath));
}

const requiredIndexPaths = [
  "docs/INDEX.md",
  "docs/modules/INDEX.md",
  "docs/tasks/INDEX.md",
  "scripts/tasks/INDEX.md",
  "work-log/tasks/INDEX.md",
];

const warningHeader =
  "<!-- Generated by scripts/core/generate-repo-indexes.mjs from metadata/*.json. Do not edit by hand. -->";

const expectedSections = {
  "docs/INDEX.md": ["modules", "tasks", "contracts"],
  "docs/modules/INDEX.md": ["modules"],
  "docs/tasks/INDEX.md": ["tasks"],
  "scripts/tasks/INDEX.md": ["tasks"],
  "work-log/tasks/INDEX.md": ["tasks"],
};

test("Phase 5 generator script exists", () => {
  assert.ok(
    exists("scripts/core/generate-repo-indexes.mjs"),
    "Missing generator script: scripts/core/generate-repo-indexes.mjs"
  );
});

test("Phase 5 generator script is deterministic (no Date or random)", () => {
  const code = read("scripts/core/generate-repo-indexes.mjs");
  const hasDateNow = code.includes("new Date()") || code.includes("Date.now()");
  const hasRandom = code.includes("Math.random()") || code.includes("crypto.random");
  assert.equal(hasDateNow, false, "Generator must not use new Date() or Date.now() — must be deterministic");
  assert.equal(hasRandom, false, "Generator must not use Math.random() or crypto.random — must be deterministic");
});

test("Phase 5 generated index files exist", () => {
  for (const indexPath of requiredIndexPaths) {
    assert.ok(exists(indexPath), `Missing generated index: ${indexPath}`);
  }
});

test("Phase 5 generated index files have warning header", () => {
  for (const indexPath of requiredIndexPaths) {
    const content = read(indexPath);
    assert.ok(
      content.startsWith(warningHeader),
      `${indexPath} must start with the generated-by warning header`
    );
  }
});

test("Phase 5 generated index files are non-empty beyond header", () => {
  for (const indexPath of requiredIndexPaths) {
    const content = read(indexPath);
    const body = content.slice(warningHeader.length).trim();
    assert.ok(body.length > 0, `${indexPath} must have content beyond the header`);
  }
});

test("Phase 5 generated index files reference metadata sources", () => {
  for (const indexPath of requiredIndexPaths) {
    const content = read(indexPath);
    const sections = expectedSections[indexPath];
    for (const section of sections) {
      assert.ok(
        content.toLowerCase().includes(section.toLowerCase()),
        `${indexPath} should reference "${section}" section from metadata sources`
      );
    }
  }
});

test("Phase 5 generated indexes are deterministic (no timestamp in content)", () => {
  for (const indexPath of requiredIndexPaths) {
    const content = read(indexPath);
    // The warning header explicitly says "Generated by scripts/core/generate-repo-indexes.mjs"
    // — verify no ISO-8601 timestamps appear in the content body
    const body = content.slice(warningHeader.length);
    const isoDatePattern = /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/;
    assert.equal(
      isoDatePattern.test(body),
      false,
      `${indexPath} must not contain ISO-8601 timestamps in its body (must be deterministic)`
    );
  }
});

test("package.json contains generate:indexes script", () => {
  const pkg = readJson("package.json");
  assert.equal(
    typeof pkg.scripts?.["generate:indexes"],
    "string",
    "Missing package.json script: generate:indexes"
  );
  assert.ok(
    pkg.scripts["generate:indexes"].includes("generate-repo-indexes.mjs"),
    "generate:indexes script must invoke scripts/core/generate-repo-indexes.mjs"
  );
});

test("Phase 5 work-log artifacts exist", () => {
  const requiredFiles = [
    "work-log/tasks/repo-architecture-contract/phases/phase-5-generated-indexes/metadata.json",
    "work-log/tasks/repo-architecture-contract/phases/phase-5-generated-indexes/plan.md",
    "work-log/tasks/repo-architecture-contract/phases/phase-5-generated-indexes/test-plan.md",
    "work-log/tasks/repo-architecture-contract/phases/phase-5-generated-indexes/audit-log.md"
  ];

  for (const file of requiredFiles) {
    assert.ok(exists(file), `Missing Phase 5 work-log artifact: ${file}`);
  }
});
